export default {
    "1": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": 0,
                "distance": 1500,
                "av": 0.003,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            }
        ],
        "text": "Drag across the screen to shoot your shield balls.\nIf any bullet/enemy hits your core, you will die."
    },

    "2": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": 0,
                "distance": 1500,
                "av": 0.003,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            },
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": Math.PI,
                "distance": 1500,
                "av": 0.003,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            }
        ],
        "text": "Can you handle 2 now?"
    },

    "3": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 40,
                "angle": 127491,
                "distance": 1500,
                "av": 0.001,
                "iv": 1,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 1,
                "bulletTime": 10000000000,
                "health": 200,
            },
        ],
        "text": "What about this tiny one?\nHe has double the health of the previous one :>"
    },

    "4": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 60,
                "angle": 0,
                "distance": 1500,
                "av": 0.001,
                "iv": 1,
                "dbc": 3,
                "cash": 50,
                "bulletNumber": 2,
                "bulletTime": 20,
                "health": 200,
            },
        ],
        "text": "This one may be a bit harder."
    },

    "5": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": -Math.PI / 2,
                "distance": 1500,
                "av": 0.006,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            },
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": Math.PI / 2,
                "distance": 1500,
                "av": 0.006,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            },
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": Math.PI,
                "distance": 1500,
                "av": 0.006,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            },
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 100,
                "angle": 0,
                "distance": 1500,
                "av": 0.006,
                "iv": 0.5,
                "dbc": 3,
                "cash": 100,
                "bulletNumber": 1,
                "bulletTime": 100,
                "health": 100,
            }
        ],
        "text": "It's only going to get harder."
    },

    "6": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 50,
                "angle": 0,
                "distance": 1500,
                "av": 0.001,
                "iv": 2,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 4,
                "bulletTime": 100,
                "health": 250,
            },
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 50,
                "angle": Math.PI,
                "distance": 1500,
                "av": 0.001,
                "iv": 2,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 4,
                "bulletTime": 100,
                "health": 250,
            },
        ],
        "text": "It's only going to get harder."
    },
    "7": {
        "enemies": [
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 50,
                "angle": 0,
                "distance": 1500,
                "av": 0.001,
                "iv": 2,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 4,
                "bulletTime": 100,
                "health": 300,
            },
            {
                "type": "basic",
                "spawnTime": 0,
                "radius": 50,
                "angle": Math.PI,
                "distance": 1500,
                "av": 0.001,
                "iv": 2,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 4,
                "bulletTime": 100,
                "health": 300,
            },
            {
                "type": "basic",
                "spawnTime": 10000,
                "radius": 50,
                "angle": -Math.PI / 2,
                "distance": 1500,
                "av": 0.001,
                "iv": 2,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 4,
                "bulletTime": 100,
                "health": 300,
            },
            {
                "type": "basic",
                "spawnTime": 10000,
                "radius": 50,
                "angle": Math.PI / 2,
                "distance": 1500,
                "av": 0.001,
                "iv": 2,
                "dbc": 3,
                "cash": 200,
                "bulletNumber": 4,
                "bulletTime": 100,
                "health": 300,
            },
        ],
        "text": "Did you think regeneration was a weak upgrade?"
    }
}